require "condensation/filters/default"
require "condensation/filters/hyperlink"
require "condensation/filters/replace_inner_html"
require "condensation/filters/days_since"
require "condensation/filters/days_until"